#!/usr/bin/env python3
import sys

if len(sys.argv[1:]) == 0:
    print('hextoascii needs an argument')
    sys.exit()

args = ''.join(sys.argv[1:])
s = args.replace('\n', '')
for i in range(0,len(s),4):
    try:
        print(s[i+3]+s[i+2]+s[i+1]+s[i], end='')
    except:
        pass
print()
