#!/bin/bash
##############################################################################
# Copyright (C) 2021  phx
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published
#    by the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
##############################################################################
read -r -d '' PROGRAM <<EOF
#include <stdio.h>
const char *test = "test";
int main() {
  printf("%p\n", (void*)test);
  return 0;
}
EOF

checkpie() {
  for i in $(seq 1 5); do
    echo -n "$i "
    ./pietest
  done
}

cd /tmp || exit
echo "$PROGRAM" > pietest.c
echo 'gcc -o pietest pietest.c:'
gcc -o pietest pietest.c
checkpie
echo
echo 'gcc -o pietest pietest.c -Wl,-no_pie:'
gcc -o pietest pietest.c -Wl,-no_pie
checkpie
rm -f pietest pietest.c
